---
title: "Untitled"
author: "Nicolas Carmona, Niklas Tillenburg, Janek Teders"
date: "December 17, 2018"
output: ioslides_presentation
---

1. raw: 21 cols
```{r}
set.seed(1234)
complete_data <- read_csv("kc_house_data.csv") %>%
  sample_n(nrow(.))

raw_data <- complete_data %>%
  slice((n()/5):n())

data_20p <- complete_data %>%
  slice(1:(n()/5))

saveRDS(raw_data, "raw_data.rds")
```

2. raw without:
    - id 
    - date
  changed:
    - sqft into sqm
    - waterfront into factor
  added:
    - month
    - week
    - wasViewed
    - renovated(factor)
    - mean_price_zip
    
    24 cols
    
```{r}
full_data <- raw_data %>%
  mutate_at(
    vars(starts_with("sqft")),
    function(x) x * 0.092903
  ) %>%
  rename_at(
    vars(starts_with("sqft")),
    function(x) str_replace(x, "sqft", "sqm")
  ) %>%
  mutate(
    week_of_year = week(date),
    month_of_year = month(date),
    renovated = factor(ifelse(yr_renovated > 0, "yes", "no")),
    wasViewed = factor(ifelse(view > 0, 1, 0)),
    waterfront = factor(waterfront)
  ) %>%
  select(-id, -date, -starts_with("sqm"), starts_with("sqm"))


first_fifth_avg <- data_20p %>%
  group_by(zipcode) %>%
  summarise(mean_price_zip = mean(price))

#result <- full_data %>%
#  left_join(., first_fifth_avg, key = zipcode) %>%
#  select(zipcode, mean_price_zip, price) 

full_data <- full_data %>%
  left_join(., first_fifth_avg, key = zipcode) %>%
  mutate(
    price = log10(price),
    mean_price_zip = log10(mean_price_zip)
  )

saveRDS(full_data, "full_data.rds")
```

# full data without outliers
```{r}
full_data_woo <- full_data %>%
  #select(-wasViewed, -renovated, -mean_price_zip) %>%
  slice(c(-11520, -3183, -6187, -8844))

saveRDS(full_data_woo, "full_data_woo.rds" )
```


#